name: Run Coverage

on:
  push:
  workflow_dispatch: {}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  run-tests:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install lcov
      run: |
        sudo apt-get install lcov
      id: lcov
    
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Run coverage
      run: forge coverage --report lcov
      env:
        RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
        RPC_HOLESKY: ${{ secrets.RPC_HOLESKY }}
        CHAIN_ID: ${{ secrets.CHAIN_ID }}
    
    - name: Prune coverage report
      run: lcov --remove ./lcov.info -o ./lcov.info.pruned 'src/test/*' 'script/*' --ignore-errors inconsistent

    - name: Generate reports
      run: mkdir report && cd report && genhtml --version && genhtml ../lcov.info.pruned -o report --ignore-errors

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: report/*